# from MGI to HGCN: high selectivity since we fix the resource URI and low selectivity from HGCN
select * where {
  service<http://localhost:3030/mgi/sparql> {
    <http://bio2rdf.org/mgi:1915545> ?p ?join .
}

  service<http://localhost:3030/hgnc/sparql> {
    ?join <http://bio2rdf.org/hgnc_vocabulary:status>	"Approved" .
    ?join <http://bio2rdf.org/hgnc_vocabulary:approved_symbol> "AAR2"
  }
}